import { CourseOutline } from "../../../../../models/academics/courseOutline";
export const courseOutline300: CourseOutline = {
  First: {
    courseInfo: [
      {
        courseCode: "ENS 301",
        courseTitle: "Introduction To Entrepreneurship and Innovation",
        creditUnit: 2,
        id: "ENS301",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 305",
        courseTitle: "Strength Of Materials I",
        creditUnit: 3,
        id: "ENG305",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 307",
        courseTitle: "Engineering Mathematics I",
        creditUnit: 3,
        id: "ENG307",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 309",
        courseTitle: "Fluid Mechanics",
        creditUnit: 3,
        id: "ENG309",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 311",
        courseTitle: "Machine Design",
        creditUnit: 2,
        id: "ENG311",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 317",
        courseTitle: "Engineering Writing and Presentation",
        creditUnit: 2,
        id: "ENG317",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 301",
        courseTitle: "Polymer Chemistry",
        creditUnit: 2,
        id: "PTE301",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 303",
        courseTitle: "Polymer Physics",
        creditUnit: 2,
        id: "PTE303",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 307",
        courseTitle: "Yarn Manufacture",
        creditUnit: 2,
        id: "PTE307",
        option: "MANDATORY",
      },
    ],
  },
  Second: {
    courseInfo: [
      {
        courseCode: "ENG 304",
        courseTitle: "Heat and Mass Transfer",
        creditUnit: 4,
        id: "ENG304",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 308",
        courseTitle: "Engineering Mathematics II",
        creditUnit: 3,
        id: "ENG308",
        option: "MANDATORY",
      },
      {
        courseCode: "ENS 302",
        courseTitle: "Business Creation, Growth and Corporate Governance",
        creditUnit: 2,
        id: "ENS302",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE302",
        courseTitle: "Chemistry Of Elastomers",
        creditUnit: 2,
        id: "PTE302",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 310",
        courseTitle: "Polymer Processing Engineering Technology",
        creditUnit: 2,
        id: "PTE310",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 314",
        courseTitle: "Man Made Fibre Production",
        creditUnit: 2,
        id: "PTE314",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 316",
        courseTitle: "Chemical Processing Of Textiles",
        creditUnit: 2,
        id: "PTE316",
        option: "MANDATORY",
      },
      {
        courseCode: "PTE 322",
        courseTitle: "Analysis and Testing of Polymer and Textiles",
        creditUnit: 2,
        id: "PTE322",
        option: "MANDATORY",
      },
      {
        courseCode: "SIW 300",
        courseTitle: "Third Year Long Vacation SIWES",
        creditUnit: 2,
        id: "PTE322",
        option: "MANDATORY",
      },
    ],
  },
};
