import { CourseOutline } from "../../../../../models/academics/courseOutline";
export const courseOutline100: CourseOutline = {
  First: {
    courseInfo: [
      {
        courseCode: "MTH 101",
        courseTitle: "Elementary Mathematics",
        creditUnit: 4,
        id: "MTH101",
        option: "MANDATORY",
      },
      {
        courseCode: "PHY 101",
        courseTitle: "General Physics I",
        creditUnit: 3,
        id: "PHY101",
        option: "MANDATORY",
      },
      {
        courseCode: "CHM 101",
        courseTitle: "General Chemistry I",
        creditUnit: 3,
        id: "CHM101",
        option: "MANDATORY",
      },
      {
        courseCode: "BIO 103",
        courseTitle: "Biology For Physical Sciences",
        creditUnit: 2,
        id: "BIO103",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 101",
        courseTitle: "Workshop Practice I",
        creditUnit: 1,
        id: "ENG101",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 103",
        courseTitle: "Engineering Drawing I",
        creditUnit: 1,
        id: "ENG103",
        option: "MANDATORY",
      },
      {
        courseCode: "GST 101",
        courseTitle: "Use Of English I",
        creditUnit: 2,
        id: "GST101",
        option: "MANDATORY",
      },
      {
        courseCode: "GST 103",
        courseTitle: "Philosophy And Logic",
        creditUnit: 1,
        id: "GST103",
        option: "MANDATORY",
      },
      {
        courseCode: "IGB 101",
        courseTitle: "Introduction to Igbo History, Culture and Literature I",
        creditUnit: 1,
        id: "IGB101",
        option: "ELECTIVE",
      },
      {
        courseCode: "FRN 101",
        courseTitle: "French Language",
        creditUnit: 1,
        id: "FRN101",
        option: "ELECTIVE",
      },
    ],
  },
  Second: {
    courseInfo: [
      {
        courseCode: "MTH 102",
        courseTitle: "Elementary Mathematics II",
        creditUnit: 4,
        id: "MTH102",
        option: "MANDATORY",
      },
      {
        courseCode: "PHY 102",
        courseTitle: "General Physics II",
        creditUnit: 3,
        id: "PHY102",
        option: "MANDATORY",
      },
      {
        courseCode: "CHM 102",
        courseTitle: "General Chemistry II",
        creditUnit: 3,
        id: "CHM102",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 102",
        courseTitle: "Workshop Practice II",
        creditUnit: 1,
        id: "ENG102",
        option: "MANDATORY",
      },
      {
        courseCode: "ENG 104",
        courseTitle: "Engineering Drawing II",
        creditUnit: 1,
        id: "ENG104",
        option: "MANDATORY",
      },
      {
        courseCode: "GST 102",
        courseTitle: "Use Of English II",
        creditUnit: 2,
        id: "GST102",
        option: "MANDATORY",
      },
      {
        courseCode: "GST 108",
        courseTitle: "Social Science I",
        creditUnit: 2,
        id: "GST108",
        option: "MANDATORY",
      },
      {
        courseCode: "GST 110",
        courseTitle: "Philosophy And Logic II",
        creditUnit: 1,
        id: "GST110",
        option: "MANDATORY",
      },
      {
        courseCode: "IGB 102",
        courseTitle: "Introduction to Igbo History, Culture and Literature II",
        creditUnit: 1,
        id: "IGB102",
        option: "ELECTIVE",
      },
      {
        courseCode: "FRN 102",
        courseTitle: "French Language",
        creditUnit: 1,
        id: "FRN102",
        option: "ELECTIVE",
      },
    ],
  },
};
